name: Build CI

on:
  pull_request: { }
  workflow_dispatch: { }

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          #          - os: ubuntu-latest
          #            arch: amd64
          #            cmake-arch: x86_64
          - os: macOS-latest
            arch: x86_64
            cmake-arch: x86_64
          - os: macOS-latest
            arch: aarch64
            cmake-arch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Install dependencies
        run: brew install meson nasm

      - name: Init submodule avif
        run: git submodule update --init --recursive

      - name: Build libavif
        run: ./gradlew :avif:darwin:buildLibAvifDarwin -PARCH=${{ matrix.arch }} -PCMAKE-ARCH=${{ matrix.cmake-arch }}

      - name: Build libavif-jvm.klb
        run: ./gradlew :avif:buildLibAvifDarwinKLib -PARCH=${{ matrix.arch }} -PCMAKE-ARCH=${{ matrix.cmake-arch }}

      - name: Upload libavif-jvm.klib
        uses: actions/upload-artifact@v3
        with:
          name: jvm-native-${{ matrix.arch }}
          path: avif/src/jvmMain/resources/*
          if-no-files-found: error

